communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.10.2/rabbitmq_delayed_message_exchange-3.10.2.ez"
#
## Extra plugins to enable
## Use this instead of `plugins` to add new pluginsmv ra  
##
extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_delayed_message_exchange"

podAnnotations:
  ad.datadoghq.com/rabbitmq.checks: |
      {
        "rabbitmq": {
          "init_config": {},
          "instances": [{"rabbitmq_api_url":"%%host%%:15672/api/","username": "datadog", "password": "b3P493gVvQx2"}]
        }
      }      