apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    hello: AgBE8q82d1T73JgWoTS54DuGP7ViGiTsvfGG01le8s0DuKHdLP3QjZDLmzwTjzG7bsYV86fBqIMtTHZo9IqbEYOTxI9fhIuOyRwlRVl/AsBPtado1r+rlvyJhD5H1nqcA/KM6ZzZnGvyJvhgmRk2yTNdG+/xq5WdICAw3T9vRT+oStPgYe2OZFJfk+6giWwyGVokElvc+9YRS280LP2C5GMfIbjolbiR3dBom/9U1rYJyF/goMEdGbSC23GxJ+qOpQWV+/sMdCEXohqMlYpQ4FmE+SOf7LXP3yzubZgj9yScU7UkhZ+iHCEGOXkYXDLbVy2xZDVq93qvhhoUunzXFeaoc3Waryo/kI19DpRrsxqnwYWdIqg1NQGyNB3de2bnrHRos9pzJKIXFj0FF6sEyDT3FhopaL0HpdllpoMGpt2IjrzaSF+im9JnwwhEY/oS4y8KSrGLQI9gEI5D5qxD8Oz7ciNS6hqSiDnFUcvcH+DnY7WZnKmO75I5sfY8HpN9py90NrJZioX49kjqn/E21c2DuVhLHX7GDyAQIFa2MFM3HPsVxkFmsIAgoMsglylGtCaeqn88NiqBbjqhtdWyqnLnsEutRzm3ncVcickUOPz4ioD/TOkFRC1NQq0BHI8T6xfqcb84NisIe2MCVUmWzoL1wZndCvRH/ojK/cqZguabzFdNTHoZ79MADe6A/8NScUpImCJz87zTYAMK+A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default
    type: Opaque

