apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: queue-shared-secrets
  namespace: default
spec:
  encryptedData:
    queue-url: AgATa20NRNHZPvP+wsT51g15HhYSic9rdgehibxZdUBRh/curc4BaQw0ABI27/+HJnjHkylB+BD5yS6fIoLiI2mYR6vcw71AzC6H9jlPM8x7Zi5FP82ECNlG4kezwTIu3oa3sdKdo/3Lh3olynXmhitbFGfprXs1fgsQXp0BLt9fvVTst+d56PNJaqrVB5YiO09fDTuW4rU1uFEdYwueSZTs5JBljpW+GdGziwryTgkSgWCVVZJ2lHUygCGknNiJfwzn00HRa0Tgl+y1+jbnTOF9NXD1S6maMwvSA8We4GQJjvttU+YlSedRia0xddMcxuJaXPpP5YmMYBz/jgLlBhyf3ZzOOyvGSYp8n3xzgk9pRigim2sfq8bHESL0gfcB/0ad6IDUeiy6RqcNduHo2aT2sUkWzny/FSJrR4nonbkT7t7bZpmgff7AKw3yt72Hs6RHSyMs2rhpj03S0ZI1v3MHk5ad+cgR9sIYzjoxFi8NovTw6xd/Vxjctk0Vb5D/ckUtuiFsZhoOyNkMOb36RelvDkcW7SimvAbnBiHuYOAX//4j8v/I3dzTjt3+mlpwcrv1WI+H+8pOt17J9u671POTyzR0Fnb5TnTui26C2UdVG3Zyhh0qSNWGbP419Ezpb1G+TSKH3+qrTZ972Oddc3rPHhz61cl32S/BdiOULn1HD+ighostfNLqOXhxdfFjfaBjZPldsh4JgAocLmTHK+X8oRVmERyFgxEV73GY2+DlLcTm08ICkL1ORPcOg58GHl7DY29e1HwfprY10LcP/zJmofOLsZomNYN6kJ0Y
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: queue-shared-secrets
      namespace: default
    type: Opaque

