apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: internal-api-shared-secrets
  namespace: default
spec:
  encryptedData:
    internal-api-url: AgA1fJ+RZ4P3/MisUXL8UegHqRaf8CNGcuZeAnE/42SiNCJyR0kOKU7mULBk83rrzNswEvVY1MXjOl467l6yINVnDDegSbUxWo6KnAshLzLSn9r/KN5wLrS5e46A7u4d+BMmrDJ7y86Ybfc4fOOq801HF2f88aODn8GMBybv3lG6LnPi/0djUCUlDQnj03wTHZPVKHv+42jqD4+0tHUMYHi2ytWYtRVYZAvZYbLabdhwI7SSycKuDqEqhyVVi/HBwSRqPojdWpwH133AURJlW7vbeFC8Es+Ent27f/BKp+tB2ONKVOWVKTKe5B3rqREYWaPaCdkqVhQbldLRZY9BAsWjektSJ2OfmqkQu2sOPUMOQojPCb4vsmnqsTxRqXO1G2+QsmRZiaexer8Y8UPWy2xvMBD/FnZpHSN2XdSNvBw9n5L5Bij6Ve0W3c07w4NerCCybPcR1ZoK1ch5lNU3utnODtSADDT3RNC4uCnYv2uD9pPe+ORdsta07DZiMBr/OCsvfBsNGCEgvbUYVKNbz2NWwLwZmbLhHM4UtSu5v+i8Q6/lI5RoIONo7GDJxm/SmL1m95z/4u3cFWgqTwysykSKfFvuARF85LckCuUgdXd9AGMWDNZRMXRkHIv0pcV6TF3rkuI06JkOI2W9gVSqTMWnLLJTJyKqkx21w/dPud8JGSWlSMLyYQhuhfxLHRbk5HnVgcNSld/BTAegtMrd22/bTqi2X/Juj65aX1BaxuEa9gtxYkQ1g/xILJaa5Me5FbT7jKUSfJXfLAbwYnKMVbseqYvWuVrvLCGlbhxH4JFvDsl61HC7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: internal-api-shared-secrets
      namespace: default
    type: Opaque

