name: Check terraform

on:
  push:
    branches:
      - 'feature/*'
      - 'patch/*'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./development/terraform
    name: Check terraform configuration
    env: 
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: us-east-1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      name: Setup terraform
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
    - name: Init
      run: terraform init
    - name: Validate
      run: terraform validate
    - name: Plan
      run: terraform plan -no-color -input=false
