name: Deploy production

on:
  push:
    tags:
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./development/terraform
    env: 
      TF_VAR_access_key: ${{ secrets.TERRAFORM_PROD_AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.TERRAFORM_PROD_AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ secrets.TERRAFORM_PROD_AWS_REGION }}
    name: Deploy terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      name: Setup terraform
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
    - name: Init
      run: terraform init
    - name: Validate
      run: terraform validate
    - name: Plan
      run: terraform plan -no-color -input=false
    - name: Poor mans manual trigger
      if: ${{ github.run_attempt== 1}}
      run: exit 1
    - name: Apply
      run: terraform apply -auto-approve